#!/bin/bash
#
# Example script for building dependencies and xReg.
# This is not pretty, but can be used in a pinch and serves well to illustrate
# the settings used for achieving a successful build.

# stop after the first failed command
set -e

# Catch errors and print helpful details before exiting
trap 'echo "Error: Command \"$BASH_COMMAND\" failed on line $LINENO with exit code $?" >&2' ERR

NEED_TO_DOWNLOAD=true
NEED_TO_BUILD_THIRD_PARTY=true
NEED_TO_START_XREG=true

DO_GUI=true

#BUILD_CONFIG="Debug"
BUILD_CONFIG="Release"

# directory of the xReg repo, assuming this script was invoked while in that directory
XREG_DIR="`pwd`"
XREG_BUILD_DIR="$XREG_DIR/build"

# Set this to a directory outside of the xReg repo in which to download and build dependencies 
DEPS_DIR="$XREG_DIR/../xreg_deps"
# get rid of the repository prefix in the path:
DEPS_DIR="$(cd "$(dirname "$DEPS_DIR")"; pwd)/$(basename "$DEPS_DIR")"

mkdir -p $DEPS_DIR
cd $DEPS_DIR

if ! [ -x "$(command -v wget)" ]; then
  echo "wget is not available, using a wrapper to curl instead."

  function wget()
  {
    FILENAME_TO_DOWNLOAD=`basename $1`
    echo "Downloading $FILENAME_TO_DOWNLOAD ..."

    curl -L -O $1
  }
fi

if [ "$NEED_TO_DOWNLOAD" = true ]; then
  echo "Downloading third party libraries..."
  
  # Choose the TBB package for your operating system:
  OS_STR=`uname -s`

  if [ "$OS_STR" == "Darwin" ]; then
    TBB_URL="https://github.com/intel/tbb/releases/download/2018_U1/tbb2018_20170919oss_mac.tgz"
  elif [ "$OS_STR" == "Linux" ]; then
    TBB_URL="https://github.com/intel/tbb/releases/download/2018_U1/tbb2018_20170919oss_lin.tgz"
  else
    TBB_URL="https://github.com/intel/tbb/releases/download/2018_U1/tbb2018_20170919oss_win.zip"
  fi

  TBB_FILE=`basename $TBB_URL`

  wget $TBB_URL

  tar xf $TBB_FILE

  rm $TBB_FILE

  BOOST_URL="https://archives.boost.io/release/1.87.0/source/boost_1_87_0.zip"

  BOOST_FILE=`basename $BOOST_URL`

  wget $BOOST_URL

  unzip -q $BOOST_FILE

  rm $BOOST_FILE

  EIGEN_URL="https://gitlab.com/libeigen/eigen/-/archive/3.4.1/eigen-3.4.1.zip"

  EIGEN_FILE=`basename $EIGEN_URL`

  wget $EIGEN_URL

  unzip -q $EIGEN_FILE

  rm $EIGEN_FILE

  VIENNACL_URL="https://github.com/viennacl/viennacl-dev/archive/release-1.7.1.zip"

  VIENNACL_FILE=`basename $VIENNACL_URL`

  wget $VIENNACL_URL

  unzip -q $VIENNACL_FILE

  rm $VIENNACL_FILE

  FMT_URL="https://github.com/fmtlib/fmt/archive/5.3.0.zip"

  FMT_FILE=`basename $FMT_URL`

  wget $FMT_URL

  unzip -q $FMT_FILE

  rm $FMT_FILE

  NLOPT_URL="https://github.com/stevengj/nlopt/archive/v2.5.0.zip"

  NLOPT_FILE=`basename $NLOPT_URL`

  wget $NLOPT_URL

  unzip -q $NLOPT_FILE

  rm $NLOPT_FILE

  VTK_URL="https://gitlab.kitware.com/vtk/vtk/-/archive/v9.6.2/vtk-v9.6.2.zip"

  wget $VTK_URL

  VTK_FILE=`basename $VTK_URL`

  unzip -q $VTK_FILE

  rm $VTK_FILE

  ITK_URL="https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.2.1/InsightToolkit-5.2.1.zip"

  ITK_FILE=`basename $ITK_URL`

  wget $ITK_URL

  unzip -q $ITK_FILE

  rm $ITK_FILE
  
  OPENCV_URL="https://github.com/opencv/opencv/archive/refs/tags/4.12.0.zip"

  OPENCV_FILE=`basename $OPENCV_URL`

  wget $OPENCV_URL

  unzip -q $OPENCV_FILE

  rm $OPENCV_FILE

  echo "Finished downloading third party libraries..."
fi

TBB_INC_DIR="$DEPS_DIR/tbb2018_20170919oss/include"
TBB_DIR="$DEPS_DIR/tbb2018_20170919oss/cmake"

BOOST_DIR="$DEPS_DIR/`ls | grep "boost_*"`"

EIGEN_DIR="$DEPS_DIR/`ls | grep "eigen-*"`"

VIENNACL_DIR="$DEPS_DIR/`ls | grep "viennacl-dev-release-*"`"

FMT_DIR="$DEPS_DIR/`ls | grep "fmt-*"`"

NLOPT_DIR="$DEPS_DIR/`ls | grep "nlopt-*"`"

VTK_DIR="$DEPS_DIR/`ls | grep "vtk-*"`"

ITK_DIR="$DEPS_DIR/`ls | grep "InsightToolkit-*"`"

OPENCV_DIR="$DEPS_DIR/`ls | grep "opencv-*"`"

echo "Finished setting third party downloaded directories..."

if [ "$NEED_TO_BUILD_THIRD_PARTY" = true ] ; then
  echo "Building third-party libraries..."

  echo "Building Eigen..."
  cd $EIGEN_DIR
  mkdir build
  cd build
  cmake ..
  cd ../../

  echo "Building fmt..."

  cd $FMT_DIR
  mkdir build
  cd build
  cmake -G Ninja .. \
    -DCMAKE_CXX_STANDARD:STRING="11" \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DFMT_USE_CPP11:BOOL=ON \
    -DFMT_TEST:BOOL=OFF \
    -DFMT_INSTALL:BOOL=ON \
    -DFMT_DOC:BOOL=OFF \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
  ninja
  cd ../../

  echo "Building nlopt..."

  cd $NLOPT_DIR
  mkdir build
  cd build
  cmake -G Ninja .. \
    -DCMAKE_CXX_STANDARD:STRING="11" \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DNLOPT_CXX:BOOL=OFF \
    -DNLOPT_PYTHON:BOOL=OFF \
    -DNLOPT_OCTAVE:BOOL=OFF \
    -DNLOPT_MATLAB:BOOL=OFF \
    -DNLOPT_GUILE:BOOL=OFF \
    -DNLOPT_SWIG:BOOL=OFF \
    -DNLOPT_LINK_PYTHON:BOOL=OFF \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
  ninja
  cd ../../

  echo "building VTK..."

  cd $VTK_DIR
  mkdir build
  cd build

  VTK_NO_RENDER_FLAGS=""
  if [ "$DO_GUI" = false ]; then
    VTK_NO_RENDER_FLAGS="-DVTK_GROUP_ENABLE_Rendering=NO"
  fi

  TBB_ROOT="$TBB_INC_DIR/.." cmake -G Ninja .. \
    -DCMAKE_CXX_STANDARD:STRING="11" \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DONLY_SHARED_LIBS:BOOL=OFF \
    -DVTK_GROUP_ENABLE_Imaging=YES \
    -DVTK_GROUP_ENABLE_Views=YES \
    -DBUILD_TESTING:BOOL=OFF \
    -DONLY_SHARED_LIBS:BOOL=OFF $VTK_NO_RENDER_FLAGS

  ninja

  cd ../..

  echo "building ITK..."

  cd $ITK_DIR
  mkdir build
  cd build

  cmake -G Ninja .. \
      -DCMAKE_CXX_FLAGS:STRING="-include cstdint" \
      -DCMAKE_C_FLAGS:STRING="-std=gnu17" \
      -DCMAKE_CXX_STANDARD:STRING="11" \
      -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
      -DBUILD_SHARED_LIBS:BOOL=OFF \
      -DBUILD_TESTING:BOOL=OFF \
      -DBUILD_EXAMPLES:BOOL=OFF \
      -DITK_USE_GPU:BOOL=OFF \
      -DModule_ITKReview:BOOL=ON \
      -DEigen3_DIR:PATH=$EIGEN_DIR/build \
      -DITK_USE_SYSTEM_EIGEN:BOOL=ON \
      -DModule_LabelErodeDilate:BOOL=ON \
      -DCMAKE_POLICY_VERSION_MINIMUM=3.5

  ninja

  cd ../..

  echo "building OpenCV..."

  cd $OPENCV_DIR
  mkdir build
  cd build

  # Need to set this OFF on MARCC (and other systems without the necessary deps)
  OPENCV_GUI_FLAGS=""
  if [ "$DO_GUI" = false ]; then
    OPENCV_GUI_FLAGS="-DBUILD_opencv_highgui:BOOL=OFF -DWITH_GSTREAMER:BOOL=OFF"
  fi

  # On Ubuntu 14.04, you may need to add this:
  # -DWITH_LAPACK=OFF

  cmake -G Ninja .. \
        -DCMAKE_CXX_STANDARD:STRING="11" \
        -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
        -DBUILD_SHARED_LIBS:BOOL=OFF \
        -DBUILD_TESTS:BOOL=OFF \
        -DBUILD_EXAMPLES:BOOL=OFF \
        -DBUILD_DOCS:BOOL=OFF \
        -DBUILD_WITH_DEBUG_INFO:BOOL=OFF \
        -DWITH_TBB:BOOL=OFF \
        -DBUILD_TBB:BOOL=OFF \
        -DWITH_IPP:BOOL=OFF \
        -DWITH_VTK:BOOL=OFF \
        -DWITH_CUBLAS:BOOL=OFF \
        -DWITH_CUDA:BOOL=OFF \
        -DWITH_OPENCL:BOOL=OFF \
        -DWITH_EIGEN:BOOL=OFF \
        -DBUILD_opencv_java_bindings_generator:BOOL=OFF \
        -DBUILD_opencv_python_tests:BOOL=OFF \
        -DBUILD_opencv_python_bindings_generator:BOOL=OFF $OPENCV_GUI_FLAGS

  ninja

  cd ../..
  
fi

# START: XREG BUILD:

if [ "$NEED_TO_START_XREG" = true ]; then
  
  mkdir $XREG_BUILD_DIR
  cd $XREG_BUILD_DIR

  cmake -G Ninja .. \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON \
    -DViennaCL_DIR:PATH="$VIENNACL_DIR" \
    -DEIGEN3_INCLUDE_DIR:PATH="$EIGEN_DIR" \
    -DBoost_INCLUDE_DIR:PATH="$BOOST_DIR" \
    -DNLopt_DIR:PATH="$NLOPT_DIR/build" \
    -DXREG_USE_LEGACY_FIND_TBB:BOOL=OFF \
    -DTBB_DIR:PATH="$TBB_DIR" \
    -DTBB_INCLUDE_DIRS:PATH=$TBB_INC_DIR \
    -Dfmt_DIR:PATH="$FMT_DIR/build" \
    -DVTK_DIR:PATH="$VTK_DIR/build" \
    -DITK_DIR:PATH="$ITK_DIR/build" \
    -DOpenCV_DIR:PATH="$OPENCV_DIR/build" \
    -DXREG_INCLUDE_GIT_HASH_IN_VER_STR:BOOL=ON

  ninja

fi

