#!/bin/bash
#
# Example script for building dependencies and xReg.
# This is not pretty, but can be used in a pinch and serves well to illustrate
# the settings used for achieving a successful build.

# stop after the first failed command
set -e

# Catch errors and print helpful details before exiting
trap 'echo "Error: Command \"$BASH_COMMAND\" failed on line $LINENO with exit code $?" >&2' ERR

NEED_TO_DOWNLOAD=true
NEED_TO_BUILD_THIRD_PARTY=true
NEED_TO_START_XREG=true

DO_GUI=true

#BUILD_CONFIG="Debug"
BUILD_CONFIG="Release"

# directory of the xReg repo, assuming this script was invoked while in that directory
XREG_DIR="`pwd`"
XREG_BUILD_DIR="$XREG_DIR/build"

# Set this to a directory outside of the xReg repo in which to download and build dependencies 
DEPS_DIR="$XREG_DIR/../xreg_deps"
# get rid of the repository prefix in the path:
DEPS_DIR="$(cd "$(dirname "$DEPS_DIR")"; pwd)/$(basename "$DEPS_DIR")"

mkdir -p $DEPS_DIR
cd $DEPS_DIR

if ! [ -x "$(command -v wget)" ]; then
  echo "wget is not available, using a wrapper to curl instead."

  function wget()
  {
    FILENAME_TO_DOWNLOAD=`basename $1`
    echo "Downloading $FILENAME_TO_DOWNLOAD ..."

    curl -L -O $1
  }
fi

if [ "$NEED_TO_DOWNLOAD" = true ]; then
  echo "Downloading third party libraries..."
  
  BOOST_URL="https://archives.boost.io/release/1.87.0/source/boost_1_87_0.zip"

  BOOST_FILE=`basename $BOOST_URL`

  wget $BOOST_URL

  unzip -q $BOOST_FILE

  rm $BOOST_FILE

  ZLIB_URL="https://www.zlib.net/zlib132.zip"

  ZLIB_FILE=`basename $ZLIB_URL`

  wget $ZLIB_URL

  unzip -q $ZLIB_FILE

  rm $ZLIB_FILE

  VTK_URL="https://gitlab.kitware.com/vtk/vtk/-/archive/v9.6.2/vtk-v9.6.2.zip"

  wget $VTK_URL

  VTK_FILE=`basename $VTK_URL`

  unzip -q $VTK_FILE

  rm $VTK_FILE

  ITK_URL="https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.4.7/InsightToolkit-5.4.7.zip"

  ITK_FILE=`basename $ITK_URL`

  wget $ITK_URL

  unzip -q $ITK_FILE

  rm $ITK_FILE
  
  OPENCV_URL="https://github.com/opencv/opencv/archive/refs/tags/4.12.0.zip"

  OPENCV_FILE=`basename $OPENCV_URL`

  wget $OPENCV_URL

  unzip -q $OPENCV_FILE

  rm $OPENCV_FILE

  echo "Finished downloading third party libraries..."
fi

BOOST_DIR="$DEPS_DIR/`ls | grep "boost_*"`"

# Eigen is bundled with xReg
EIGEN_DIR="$XREG_DIR/third_party/eigen-3.4.1"
EIGEN_BUILD_DIR="$DEPS_DIR/eigen_build"

ZLIB_DIR="$DEPS_DIR/`ls | grep "zlib-*"`"

VTK_DIR="$DEPS_DIR/`ls | grep "vtk-*"`"

ITK_DIR="$DEPS_DIR/`ls | grep "InsightToolkit-*"`"

OPENCV_DIR="$DEPS_DIR/`ls | grep "opencv-*"`"

echo "Finished setting third party downloaded directories..."

if [ "$NEED_TO_BUILD_THIRD_PARTY" = true ] ; then
  echo "Building third-party libraries..."

  echo "Configuring Eigen..."
  # Eigen is header only, this generates the CMake config files needed by ITK
  mkdir -p $EIGEN_BUILD_DIR
  cd $EIGEN_BUILD_DIR
  cmake $EIGEN_DIR \
    -DBUILD_TESTING:BOOL=OFF \
    -DEIGEN_BUILD_DOC:BOOL=OFF \
    -DEIGEN_BUILD_BLAS:BOOL=OFF \
    -DEIGEN_BUILD_LAPACK:BOOL=OFF \
    -DEIGEN_BUILD_DEMOS:BOOL=OFF \
    -DCMAKE_EXPORT_PACKAGE_REGISTRY:BOOL=OFF
  cd $DEPS_DIR

  echo "building ZLIB..."

  cd $ZLIB_DIR
  mkdir build
  cd build
  cmake -G Ninja .. \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DZLIB_BUILD_SHARED:BOOL=OFF \
    -DZLIB_BUILD_STATIC:BOOL=ON \
    -DZLIB_BUILD_TESTING:BOOL=OFF \
    -DCMAKE_INSTALL_PREFIX:PATH=$ZLIB_DIR/install
  ninja
  ninja install
  cd ../../

  echo "building VTK..."

  cd $VTK_DIR
  mkdir build
  cd build

  VTK_NO_RENDER_FLAGS=""
  if [ "$DO_GUI" = false ]; then
    VTK_NO_RENDER_FLAGS="-DVTK_GROUP_ENABLE_Rendering=NO"
  fi

  cmake -G Ninja .. \
    -DCMAKE_CXX_STANDARD:STRING="17" \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DONLY_SHARED_LIBS:BOOL=OFF \
    -DVTK_GROUP_ENABLE_Imaging=YES \
    -DVTK_GROUP_ENABLE_Views=YES \
    -DBUILD_TESTING:BOOL=OFF \
    -DONLY_SHARED_LIBS:BOOL=OFF $VTK_NO_RENDER_FLAGS

  ninja

  cd ../..

  echo "building ITK..."

  cd $ITK_DIR
  mkdir build
  cd build

  cmake -G Ninja .. \
      -DCMAKE_CXX_STANDARD:STRING="17" \
      -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
      -DBUILD_SHARED_LIBS:BOOL=OFF \
      -DBUILD_TESTING:BOOL=OFF \
      -DBUILD_EXAMPLES:BOOL=OFF \
      -DITK_USE_GPU:BOOL=OFF \
      -DModule_ITKReview:BOOL=ON \
      -DEigen3_DIR:PATH=$EIGEN_BUILD_DIR \
      -DITK_USE_SYSTEM_EIGEN:BOOL=ON \
      -DITK_USE_SYSTEM_ZLIB:BOOL=ON \
      -DZLIB_ROOT:PATH=$ZLIB_DIR/install \
      -DModule_LabelErodeDilate:BOOL=ON \
      -DCMAKE_POLICY_VERSION_MINIMUM=3.5

  ninja

  cd ../..

  echo "building OpenCV..."

  cd $OPENCV_DIR
  mkdir build
  cd build

  # Need to set this OFF on MARCC (and other systems without the necessary deps)
  OPENCV_GUI_FLAGS=""
  if [ "$DO_GUI" = false ]; then
    OPENCV_GUI_FLAGS="-DBUILD_opencv_highgui:BOOL=OFF -DWITH_GSTREAMER:BOOL=OFF"
  fi

  # On Ubuntu 14.04, you may need to add this:
  # -DWITH_LAPACK=OFF

  cmake -G Ninja .. \
        -DCMAKE_CXX_STANDARD:STRING="17" \
        -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
        -DBUILD_SHARED_LIBS:BOOL=OFF \
        -DBUILD_TESTS:BOOL=OFF \
        -DBUILD_EXAMPLES:BOOL=OFF \
        -DBUILD_DOCS:BOOL=OFF \
        -DBUILD_WITH_DEBUG_INFO:BOOL=OFF \
        -DWITH_TBB:BOOL=OFF \
        -DBUILD_TBB:BOOL=OFF \
        -DWITH_IPP:BOOL=OFF \
        -DWITH_VTK:BOOL=OFF \
        -DWITH_CUBLAS:BOOL=OFF \
        -DWITH_CUDA:BOOL=OFF \
        -DWITH_OPENCL:BOOL=OFF \
        -DWITH_EIGEN:BOOL=OFF \
        -DWITH_TIFF:BOOL=OFF \
        -DBUILD_TIFF:BOOL=OFF \
        -DBUILD_ZLIB:BOOL=OFF \
        -DZLIB_ROOT:PATH=$ZLIB_DIR/install \
        -DBUILD_opencv_java_bindings_generator:BOOL=OFF \
        -DBUILD_opencv_python_tests:BOOL=OFF \
        -DBUILD_opencv_python_bindings_generator:BOOL=OFF $OPENCV_GUI_FLAGS

  ninja

  cd ../..
  
fi

# START: XREG BUILD:

if [ "$NEED_TO_START_XREG" = true ]; then
  echo "Building xreg..."

  mkdir $XREG_BUILD_DIR
  cd $XREG_BUILD_DIR

  cmake -G Ninja .. \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON \
    -DBoost_INCLUDE_DIR:PATH="$BOOST_DIR" \
    -DVTK_DIR:PATH="$VTK_DIR/build" \
    -DITK_DIR:PATH="$ITK_DIR/build" \
    -DOpenCV_DIR:PATH="$OPENCV_DIR/build" \
    -DXREG_INCLUDE_GIT_HASH_IN_VER_STR:BOOL=ON

  ninja

fi

