# This Docker file is used to build an ubuntu image with the necessary
# packages installed to complete an xReg build (along with its dependencies)

ARG os_version=26.04

FROM ubuntu:${os_version}

# DEBIAN_FRONTEND=noninteractive is needed to avoid an interactive prompt
# to set the timezone with images of 20.04 or more recent.

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      cmake \
      ninja-build \
      libtbb-dev \
      wget \
      libssl-dev \
      git \
      libglew-dev \
      libxt-dev && \
    rm -rf /var/lib/apt/lists/*
