# This Docker file is used to build an image with all of the dependencies needed to
# build the xReg library and should be tagged something like xreg-deps-${os_name}-${os_version}
# (e.g. xreg-deps-ubuntu-16.04)

# choose either ubuntu or centos
ARG os_name=ubuntu

# for ubuntu choose 16.04, 18.04, or 20.04
# for centos choose 7 or 8
ARG os_version=26.04

# e.g. by running Dockerfile.ubuntu_dev_base or Dockerfile.centos_dev_base
FROM xreg-dev-base-${os_name}-${os_version} as xreg-dev-base-cust-deps

WORKDIR /

RUN mkdir ffmpeg_dl && cd ffmpeg_dl && \
    wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
    tar xf ffmpeg-release-amd64-static.tar.xz && \
    mkdir -p /usr/local/bin && \
    mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin && \
    cd / && rm -rf ffmpeg_dl

FROM xreg-dev-base-cust-deps as xreg-deps

WORKDIR /

# bring in boost header only
RUN mkdir boost_dl && cd boost_dl && \
    wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2 && \
    tar xf boost_1_87_0.tar.bz2 && cd boost_1_87_0 && mv boost /usr/local/include && \
    cd / && rm -rf boost_dl

# bring in eigen header only, but needs to install cmake files
RUN mkdir eigen_dl && cd eigen_dl && \
    wget https://gitlab.com/libeigen/eigen/-/archive/3.4.1/eigen-3.4.1.tar.bz2 && \
    tar xf eigen-3.4.1.tar.bz2 && cd eigen-3.4.1 && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH="/usr/local" \
          -DINCLUDE_INSTALL_DIR:PATH="/usr/local/include" \
          .. && \
    cmake --build . && cmake --build . --target install && \
    cd / && rm -rf eigen_dl

# bring in viennacl header only
RUN mkdir viennacl_dl && cd viennacl_dl && \
    wget https://github.com/viennacl/viennacl-dev/archive/release-1.7.1.tar.gz && \
    tar xf release-1.7.1.tar.gz && cd viennacl-dev-release-1.7.1 && mv viennacl /usr/local/include && \
    cd / && rm -rf viennacl_dl

# build format
RUN mkdir fmt_build && cd fmt_build && \
    wget https://github.com/fmtlib/fmt/archive/5.3.0.tar.gz && \
    tar xf 5.3.0.tar.gz && cd fmt-5.3.0 && \
    mkdir build && cd build && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON \
                   -DCMAKE_CXX_STANDARD:STRING="11" -DFMT_USE_CPP11:BOOL=ON \
                   -DFMT_TEST:BOOL=OFF -DFMT_INSTALL:BOOL=ON \
                   -DFMT_DOC:BOOL=OFF \
                   -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          .. && \
    cmake --build . && cmake --build . --target install && \
    cd / && rm -rf fmt_build

# build nlopt
RUN mkdir nlopt_build && cd nlopt_build && \
    wget https://github.com/stevengj/nlopt/archive/v2.5.0.tar.gz && \
    tar xf v2.5.0.tar.gz && cd nlopt-2.5.0 && \
    mkdir build && cd build && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON \
                   -DCMAKE_CXX_STANDARD:STRING="11" \
                   -DNLOPT_CXX:BOOL=OFF -DNLOPT_PYTHON:BOOL=OFF \
                   -DNLOPT_OCTAVE:BOOL=OFF -DNLOPT_MATLAB:BOOL=OFF \
                   -DNLOPT_GUILE:BOOL=OFF -DNLOPT_SWIG:BOOL=OFF \
                   -DNLOPT_LINK_PYTHON:BOOL=OFF \
                   -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
         .. && \
    cmake --build . && cmake --build . --target install && \
    cd / && rm -rf nlopt_build

# build ITK
RUN mkdir itk_build && cd itk_build && \
    wget https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.2.1/InsightToolkit-5.2.1.tar.gz && \
    tar xf InsightToolkit-5.2.1.tar.gz && cd InsightToolkit-5.2.1 && \
    mkdir build && cd build && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON \
          -DCMAKE_CXX_STANDARD:STRING="11" \
          -DCMAKE_CXX_FLAGS:STRING="-include cstdint" \
          -DCMAKE_C_FLAGS:STRING="-std=gnu17" \
          -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF \
          -DITK_USE_GPU:BOOL=OFF -DModule_ITKReview:BOOL=ON \
          -DModule_LabelErodeDilate:BOOL=ON \
          -DITK_USE_SYSTEM_EIGEN=ON \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
         .. && \
    cmake --build . && cmake --build . --target install && \
    cd / && rm -rf itk_build

# build OpenCV
RUN mkdir opencv_build && cd opencv_build && \
    wget https://github.com/opencv/opencv/archive/refs/tags/4.12.0.tar.gz && \
    tar xf 4.12.0.tar.gz && cd opencv-4.12.0 && \
    mkdir build && cd build && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON \
                   -DCMAKE_CXX_STANDARD:STRING="11" \
                   -DBUILD_TESTS:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF \
                   -DBUILD_DOCS:BOOL=OFF -DBUILD_WITH_DEBUG_INFO:BOOL=OFF \
                   -DWITH_TBB:BOOL=ON -DBUILD_TBB:BOOL=OFF \
                   -DWITH_IPP:BOOL=OFF -DWITH_VTK:BOOL=OFF \
                   -DWITH_CUBLAS:BOOL=OFF -DWITH_CUDA:BOOL=OFF \
                   -DWITH_OPENCL:BOOL=OFF \
                   -DBUILD_opencv_java_bindings_generator:BOOL=OFF \
                   -DBUILD_opencv_python_tests:BOOL=OFF \
                   -DBUILD_opencv_python_bindings_generator:BOOL=OFF \
                   -DBUILD_opencv_highgui:BOOL=OFF -DWITH_GSTREAMER:BOOL=OFF \
         .. && \
    cmake --build . && cmake --build . --target install && \
    cd / && rm -rf opencv_build
    
# build VTK, note --parallel 2 is used in order to avoid OOM errors
RUN mkdir vtk_build && cd vtk_build && \
    wget https://vtk.org/files/release/9.6/VTK-9.6.2.tar.gz && \
    tar xf VTK-9.6.2.tar.gz && cd VTK-9.6.2 && \
    mkdir build && cd build && \
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON \
          -DCMAKE_CXX_STANDARD:STRING="11" \
          -DVTK_GROUP_ENABLE_Imaging=YES -DVTK_GROUP_ENABLE_Views=YES \
          -DBUILD_TESTING:BOOL=OFF \
          -DVTK_SMP_IMPLEMENTATION_TYPE:STRING="TBB" \
         .. && \
    cmake --build . --parallel 2 && cmake --build . --target install && \
    cd / && rm -rf vtk_build
