# GitHub action to build software.
# The Linux build uses a pre-built dependency container image.
# The Windows and MacOS builds build dependencies each run.

name: Build
on:
  pull_request:

jobs:
  ubuntu_26_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-26.04:latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: ./dist/ubuntu_dist_pkgs
        shell: bash
      - run: ./.github/workflows/linux_make_dist ubuntu-26.04
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-26.04-build
          path: xreg-ubuntu-26.04.tar.gz
  
  ubuntu_24_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-24.04:latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: ./dist/ubuntu_dist_pkgs
        shell: bash
      - run: ./.github/workflows/linux_make_dist ubuntu-24.04
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-build
          path: xreg-ubuntu-24.04.tar.gz
  
  ubuntu_22_04_build:
    runs-on: ubuntu-latest
    container: ghcr.io/rg2/xreg-deps-ubuntu-22.04:latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.github/workflows/linux_cmake_build
        shell: bash
      - run: ./dist/ubuntu_dist_pkgs
        shell: bash
      - run: ./.github/workflows/linux_make_dist ubuntu-22.04
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-22.04-build
          path: xreg-ubuntu-22.04.tar.gz

#  windows_build:
#    runs-on: windows-2022
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ilammy/msvc-dev-cmd@v1
#      - run: example_build_script_win.cmd
#        shell: cmd
#      - run: .github\workflows\win_make_dist.cmd
#        shell: cmd
#      - uses: actions/upload-artifact@v4
#        with:
#          name: win-64-build
#          path: xreg-win64.zip

#  macos_build:
#    runs-on: macos-15-intel
#
#    steps:
#      - uses: actions/checkout@v4
#      - run: brew install ninja
#      - run: XREG_INSTALL_DIR="$HOME/xreg_install" ./example_build_script_2
#        shell: bash
#      - run: mkdir xreg-macos-15
#      - run: python3 ./dist/make_macos_dist.py $HOME/xreg_install xreg-macos-15 ../xreg_deps_install
#      - run: cp LICENSE xreg-macos-15 && cp ./dist/dist_readme/README.txt xreg-macos-15
#      - run: tar czf xreg-macos-15.tar.gz xreg-macos-15
#      - uses: actions/upload-artifact@v4
#        with:
#          name: macos-15-build
#          path: xreg-macos-15.tar.gz
